version: '2.1'

orbs:
  gcp-cli-2: circleci/gcp-cli@2.4.1
  gcp-cli-3: circleci/gcp-cli@3.1.1

jobs:
  cli:
    parameters:
      orb-version:
        type: integer
      cli-version:
        type: string
        default: '463.0.0'
    machine:
      image: windows-server-2019-vs2019:2023.10.1
    steps:
      - when:
          condition:
            equal: [ 2, << parameters.orb-version >> ]
          steps:
            - gcp-cli-2/install:
                version: << parameters.cli-version >>
      - when:
          condition:
            equal: [ 3, << parameters.orb-version >> ]
          steps:
            - gcp-cli-3/install:
                version: << parameters.cli-version >>


workflows:
  gcp:
    jobs:
      - cli:
          matrix:
            parameters:
              orb-version:
                - 2
                - 3
