version: '2.1'

orbs: 
  win: circleci/windows@4.1.1

jobs:
  envvar:
    executor: win/server-2022
    environment:
      APP_VERSION: "19.0"
    steps:
      - run:
          shell: powershell.exe
          command: |
            New-Variable -Name "targetFolder" -Visibility Public -Value "foo\bar\$Env:APP_VERSION"
            $targetFolder
      - run:
          shell: powershell.exe
          command: |
            $targetFolder
workflows:
  my-workflow:
    jobs:
      - envvar
