version: '2.1'

orbs: 
  win: circleci/windows@4.1.1

jobs:
  win-goinstall-test:
    executor:
      name: win/server-2019
      size: "medium"

    working_directory: c:/project

    steps:
      - run:
          name: check
          shell: bash.exe
          command: go version
      - run:
          name: install go via Chocolatey
          shell: bash.exe
          command: choco install golang
      - run:
          name: check
          shell: bash.exe
          command: go version
