version: 2.1

executors:
  windows:
    machine:
      image: windows-server-2022-gui:current
      resource_class: windows.medium
  linux:
    machine:
      image: ubuntu-2204:current
      resource_class: medium
jobs:
  tests:
    parameters:
      exec:
        type: executor
    executor: << parameters.exec >>
    steps:
      - checkout
      - run:
          name: Glob packages
          command: |
            circleci tests glob "tests/**/*.spec.js"
      - run:
          name: Glob packages (try exclude unit subfolder)
          command: |
            circleci tests glob "tests/[!unit]**/*.spec.js"


workflows:
  folders:
    jobs:
      - tests:
          matrix:
            parameters:
              exec:
                - windows
                - linux
