version: '2.1'

orbs: 
  win: circleci/windows@4.1.1

jobs:
  gui-edge:
    machine:
      image: windows-server-2022-gui:edge
      resource_class: windows.large
    steps:
      - run:
          name: list installed packages
          command: choco list --localonly
      - run:
          shell: bash.exe
          name: look up build tools
          command: which visualstudio2022buildtools
      - run: npm config set msvs_version 2022 --global 

workflows:
  my-workflow:
    jobs:
      - gui-edge
