version: '2.1'

orbs: 
  win: circleci/windows@4.1.1
  node: circleci/node@5.0.2

jobs:
  node-install:
    parallelism: 1
    executor:
      name: win/server-2022
      shell: bash.exe
    steps:
      - checkout
      - run:
          name: Check current version of NVM
          command: |
            nvm --version
#       - run:
#           name: Reinstall NVM (newer version)
#           command: |
#             # Existing issue with NVM-windows 1.1.7
#             # See https://github.com/npm/cli/issues/4234

#             choco uninstall nvm --confirm
#             choco uninstall nvm.portable --confirm
#             choco install nvm
#             choco install nvm.portable
#       - run:
#           name: Check current version of NVM
#           command: |
#             # confirm NVM > 1.1.7 installed
#             nvm --version          
#       - run:
#           name: Preparing Additional Environment Variables
#           command: |
#             echo export STEAMWORKS_SDK_PATH=`pwd`/steamworks-sdk >> $BASH_ENV
#             echo export PATH="/c/Program\\ Files/Git/mingw64/libexec/git-core:\$PATH" >> $BASH_ENV
      - run: |
          # perhaps yarn should be installed via NPM instead
          curl -o- -L https://yarnpkg.com/install.sh | bash
          echo 'export PATH="$HOME/.yarn/bin:$HOME/.config/yarn/global/node_modules/.bin:$PATH"' >> $BASH_ENV
      - run: |
          # see https://github.com/coreybutler/nvm-windows/issues/674#issuecomment-943523487
          rm -r "${NVM_SYMLINK}"
      - node/install:
          # install-yarn: true
          node-version: '16.15.0'
      - run: nvm use 16.15.0
      - run: |
          node --version
          npm --version
          yarn --version
      - run: yarn global add node-gyp
      - restore_cache:
          keys:
            - v1-deps-{{ checksum "yarn.lock" }}
      - node/install-packages:
          # do not use cache, since the Orb will try to create files in /tmp/* folder
          # in short, Windows is not supported for the Node orb.
          # see top description under https://circleci.com/developer/orbs/orb/circleci/node
          with-cache: false
          override-ci-command: yarn install --frozen-lockfile
      - save_cache:
          key: v1-deps-{{ checksum "yarn.lock" }}
          path: node_modules

workflows:
  my-workflow:
    jobs:
      - node-install
