version: '2.1'

orbs: 
  win: circleci/windows@4.1.1
  node: circleci/node@5.0.2

jobs:
  node-install:
    parallelism: 1
    executor:
      name: win/server-2022
      shell: bash.exe
    steps:
      - run:
          name: Install clang and Rust
          command: |
            choco feature enable -n=allowGlobalConfirmation
            
            choco install llvm
            choco install rust
      - run:
          name: check Rust
          command: rustc

workflows:
  my-workflow:
    jobs:
      - node-install
