version: '2.1'

orbs: 
  win: circleci/windows@4.1.1
  
executors:
  win-2022:
    machine:
      image: windows-server-2022-gui:current
    shell: powershell.exe -ExecutionPolicy Bypass
    resource_class: windows.medium
    working_directory: C:\projects\q

jobs:
  docker-build:
    executor: win-2022
    steps:
      - checkout
      - run:
          command: |
            docker build -t customwin -f ./.circleci/Dockerfile .
            docker image ls

workflows:
  my-workflow:
    jobs:
      - docker-build
