version: '2.1'

orbs:
  gcp-cli-2: circleci/gcp-cli@2.4.1
  gcp-cli-3: circleci/gcp-cli@3.1.1

jobs:
  cli:
    parameters:
      orb-version:
        type: string
    machine:
      image: windows-server-2019-vs2019:2023.10.1
    steps:
      - gcp-cli-<< parameters.orb-version >>/install:
          version: '463.0.0'
          

workflows:
  gcp:
    jobs:
      - cli:
          matrix:
            parameters:
              orb-version:
                - '2'
                - '3'
