version: '2.1'

orbs: 
  win: circleci/windows@4.1.1

jobs:
  envvar:
    executor: win/server-2022
    environment:
      APP_VERSION: "19.0"
    steps:
      - run:
          shell: bash.exe
          command: |
            targetFolder="${APP_VERSION}"
            echo $targetFolder
            
            echo "export targetFolder='${APP_VERSION}'" >> $BASH_ENV
      - run:
          shell: bash.exe
          command: |
            echo $targetFolder
workflows:
  my-workflow:
    jobs:
      - envvar
