version: '2.1'
orbs:
  win: circleci/windows@2.4

jobs:
  shallow-checkout:
    executor:
      name: win/default
      size: medium
    steps:
      - run: |
          mkdir $HOME/.ssh -ea 0
          printf 'github.com ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEAq2A7hRGmdnm9tUDbO9IDSwBK6TbQa+PXYPCPy6rbTrTtw7PHkccKrpp0yVhp5HdEIcKr6pLlVDBfOLX9QUsyCOV0wzfjIJNlGEYsdlLJizHhbn2mUjvSAHQqZETYP81eFzLQNnPHt4EVVUh7VfDESU84KezmD5QlWpXLmvU31/yMf+Se8xhHTvKSCZIFImWwoG6mbUoWf9nzpIoaSjB+weqqUUmpaaasXVal72J+UX2B+2RPW3RcT0eOzQgqlJL3RKrTJvdsjE3JEAvGq3lGHSZXy28G3skua2SmVi/w4yCE6gbODqnTWlg7+wC604ydGXA8VJiS5ap43JXiUFFAaQ==
          github.com ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBEmKSENjQEezOmxkZMy7opKgwFB9nkt5YRrYMjNuG5N87uRgg6CLrbo5wAdT/y6v0mKV0U2w0WZ2YB/++Tpockg=
          github.com ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOMqqnkVzrm0SdG6UOoqKLsabgH5C9okWi0dh2l9GKJl
          ' >> ~/.ssh/known_hosts
      - add_ssh_keys:
          fingerprints:
            - "cc:b6:1c:97:38:eb:6c:fb:9a:2f:00:06:6e:4d:9e:8c"
      - run: |
          git clone --depth 1 $env:CIRCLE_REPOSITORY_URL .
  build:
    executor:
      name: win/default
      size: medium
    steps:
      - run:
          name: Profile CPU and memory usage (background)
          background: true
          command: |
            while ($true) {
                write-host "---------CPU"
                wmic cpu get loadpercentage
                write-host "---------Memory"
                tasklist
                write-host "---------"
                start-sleep -Seconds 1
                
            }    
      - checkout
      - run: 'Write-Host ''Hello, Windows'''
      

workflows:
  my-workflow:
    jobs:
      # - build
      - shallow-checkout
