version: '2.1'

orbs: 
  win: circleci/windows@4.1.1

jobs:
  check-node:
    executor: win/server-2019
    steps:
      - checkout
      - run:
          shell: bash.exe
          command: |
            node -v
            npm -v

workflows:
  my-workflow:
    jobs:
      - check-node
