version: 2.1

orbs:
  win: circleci/windows@5.0

jobs:
  build:
    executor:
     name: win/default
     shell: powershell.exe
    working_directory: C:\\Users\\circleci\\project
    parallelism: 10
    steps:
        - run: curl https://raw.githubusercontent.com/owenjoliver/open_sandbox/main/SilentInstall.iss -O C:\\Users\\circleci\\SilentInstall.iss
        - run: dir C:\\Users\\circleci
        - run: type C:\\Users\\circleci\\SilentInstall.iss
        - run: 
            command: |
              Invoke-WebRequest -Uri https://installers.ilok.com/iloklicensemanager/LicenseSupportInstallerWin64.zip -OutFile C:\\Users\\circleci\\License.zip
              Expand-Archive -Path C:\\Users\\circleci\\License.zip -DestinationPath C:\\Users\\circleci\\
            shell: powershell.exe
        - run: 
            command: |
              & 'C:\\Users\\circleci\\LicenseSupportInstallerWin64_v5.7.1_fbd47960\\License Support Win64.exe' -s -f1\u201CC:\\Users\\circleci\\SilentInstall.iss\u201D
            shell: powershell.exe
        - run: dir 'C:\\Program Files (x86)\\iLok License Manager\\'

workflows:
  workflow:
    jobs:
      - build
